# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [62]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [63]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [3]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [64]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [65]:
from sklearn.model_selection import train_test_split

In [67]:
y= data['MEDV']
X = data[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']]


X_train, X_test,y_train,  y_test = train_test_split(X, y,test_size=0.2,random_state=7)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [68]:
# Your code here :
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [73]:
y_pred =model.predict(X_test)
y_pred

ytest_pred =model.predict(X_train)
ytest_pred

array([15.98237443, 19.86714594, 21.72955319, 15.46137268, 12.52640166,
       25.51964931, 24.97917585, 21.48243747, 16.54605647, 26.00916474,
       19.07697984, 21.20953356,  8.64962747, 24.7376806 , 13.93958401,
       29.21407422, 18.22888471, 20.60955292, 17.04202539, 24.43690105,
       24.5743658 , 36.62185262, 14.68962108, 33.69004608, 21.78343436,
       28.93922382, 35.98451105, 32.07700429, 22.6888288 , 22.04120254,
       20.15418603, 28.49211715, 24.96242816, 15.69897841, 34.48311516,
       32.21794275, 15.95116405, 23.76673632, 14.03738326, 26.84882738,
       25.11317648, 24.32572959, 30.78034053, 15.50491043, 31.65319729,
       14.00846272, 30.27335437, 24.47426975, 24.47682123,  6.32226233,
       17.81820769,  5.02379134, 16.08891967, 15.38756758, 16.34562845,
       41.17867526, 26.53867891, 25.19314046, 28.39549154,  5.36123484,
       26.74494501, 20.63398597, 25.57095909, 32.9945366 ,  9.9573188 ,
       28.31420656, 33.00882023,  6.5729042 , 23.91050209, 20.60

## 3. Calculate and print R-squared for both the training and the testing set.

In [70]:
from sklearn.metrics import r2_score

r2_test = r2_score(y_test, y_pred)
r2_train = r2_score(y_train, ytest_pred)

r2_test,r2_train


(0.5785415472763422, 0.7698532963729757)

## 4. Calculate and print mean squared error for both the training and the testing set.

In [ ]:
# Your code here :
from sklearn.metrics import mean_squared_error 

test_MSR = mean_squared_error(y_pred,y_test)
train_MSR = mean_squared_error(ytest_pred,y_train)
test_MSR,train_MSR


(34.0564813488745, 19.63871731137543)

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [77]:
from sklearn.metrics import mean_absolute_error
test_MAE = mean_absolute_error(y_pred , y_test)
train_MAE = mean_absolute_error(ytest_pred , y_train)
test_MAE,train_MAE

(3.780762909174946, 3.106300428127976)

## Classification Model Evaluation

In [78]:
from sklearn.datasets import load_iris
data = load_iris()

In [79]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [80]:
column_names = data.feature_names


In [81]:
df = pd.DataFrame(data['data'],columns=column_names)

In [82]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [83]:
target = pd.DataFrame(data.target)
target

0
0    0
1    0
2    0
3    0
4    0
..  ..
145  2
146  2
147  2
148  2
149  2

[150 rows x 1 columns]

In [84]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [85]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [ ]:

y= target
X = df


X_train02, X_test02 ,y_train02 ,  y_test02 = train_test_split(X, y,test_size=0.2,random_state=7)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [ ]:
from sklearn.linear_model import LogisticRegression

model02 = LogisticRegression()
model02.fit(X_train02,y_train02)

LogisticRegression()

In [94]:
y_pred02 =model02.predict(X_test02)
y_pred02

ytest_pred02 =model02.predict(X_train02)
ytest_pred02

array([2, 1, 0, 2, 1, 0, 0, 0, 0, 2, 2, 1, 2, 2, 1, 0, 1, 1, 2, 0, 0, 0,
       2, 0, 2, 1, 1, 1, 0, 0, 0, 1, 2, 1, 1, 0, 2, 0, 0, 2, 2, 0, 2, 0,
       1, 2, 1, 0, 1, 0, 2, 2, 1, 0, 0, 1, 2, 0, 2, 2, 1, 0, 1, 0, 2, 2,
       0, 0, 2, 1, 2, 2, 1, 0, 0, 2, 0, 0, 2, 2, 2, 1, 1, 0, 2, 0, 0, 1,
       1, 2, 0, 1, 1, 2, 2, 1, 2, 0, 1, 1, 0, 0, 0, 1, 1, 0, 2, 2, 1, 2,
       0, 2, 1, 1, 0, 2, 1, 2, 1, 0])

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [98]:
from sklearn.metrics import accuracy_score
acc_test = accuracy_score(y_test02, y_pred02)
acc_train = accuracy_score(y_train02, ytest_pred02)
acc_train,acc_test

(0.9916666666666667, 0.8666666666666667)

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [99]:
from sklearn.metrics import balanced_accuracy_score

bacc_test = balanced_accuracy_score(y_test02, y_pred02)
bacc_train = balanced_accuracy_score(y_train02, ytest_pred02)
bacc_train,bacc_test

(0.9912280701754387, 0.883838383838384)

## 10. Calculate and print the precision score for both the training and the testing set.

In [102]:
from sklearn.metrics import precision_score

pc_test = precision_score(y_test02, y_pred02, average=None)
pc_train = precision_score(y_train02, ytest_pred02, average=None)
pc_train,pc_test

(array([1.   , 1.   , 0.975]), array([1.        , 0.83333333, 0.81818182]))

## 11. Calculate and print the recall score for both the training and the testing set.

In [103]:
from sklearn.metrics import recall_score

rc_test = recall_score(y_test02, y_pred02, average=None)
rc_train = recall_score(y_train02, ytest_pred02, average=None)
rc_train,rc_test

(array([1.        , 0.97368421, 1.        ]),
 array([1.        , 0.83333333, 0.81818182]))

## 12. Calculate and print the F1 score for both the training and the testing set.

In [105]:
from sklearn.metrics import f1_score

f1_test = f1_score(y_test02, y_pred02, average=None)
f1_train = f1_score(y_train02, ytest_pred02, average=None)
f1_train, f1_test

(array([1.        , 0.98666667, 0.98734177]),
 array([1.        , 0.83333333, 0.81818182]))

## 13. Generate confusion matrices for both the training and the testing set.

In [107]:
from sklearn.metrics import confusion_matrix

conf_test = confusion_matrix(y_test02, y_pred02)
conf_train = confusion_matrix(y_train02, ytest_pred02)
conf_train, conf_test

(array([[43,  0,  0],
        [ 0, 37,  1],
        [ 0,  0, 39]], dtype=int64),
 array([[ 7,  0,  0],
        [ 0, 10,  2],
        [ 0,  2,  9]], dtype=int64))

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [26]:
# Have fun here !